### ISSUE TITLE
Enhanced Sound Remixer

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#10]
From MM-NEATv2: https://github.com/schrum2/MM-NEATv2/issues/435

**Comment by schrum2** [comment]
A simple idea that came out of a meeting with Amy Hoover is to use recurrent CPPNs instead of resetting the activation for each query. I feel like we would have tried this, but I'm not sure. It is a simple thing worth trying

**Comment by drallensmith** [comment]
One question with recurrent networks is how many times to apply the input before reading the output; I would suspect this may differ between CPPNs and other uses.

**Comment by schrum2** [comment]
If Breedesizer makes sense, then you can take a shot at this remix version @annazwicker . I think there is already a class in MM-NEAT to address this, but I'm not sure if it does anything interesting. Note that this issue is so old, it goes back to the previous version of MM-NEAT ... you can read the original issue description in the link from the top of this thread.

Doing something that is a small tweak of Breedesizer could be a good stepping stone to doing something more interesting with sound.

**Comment by annazwicker** [comment]
Pitch output: changing the octave in which the output occurs.  I'm not entirely sure what this would look like.  I'm assuming changing pitch is a physics related concept, so I'm not sure what formulas would be used to make this happen.  I'm also not sure how this would appear to the user.  Since there are multiple octaves, would it be possible to create a dropdown box option, or would a slider be a better option (the only potential problem with a slider is octaves only come in integers, not doubles, so a slider would have to likely round to the nearest octave).

Adding a second line to an output: rather than just a single note, is there a way to add 2+ notes.  For example, some of the outputs produce a single, sustained A (letter name of a pitch, A - G).  Would it be possible to add another note so the same output could produce two sustained notes like A and C?  Adding another notes produces chords which provokes another possibility: could you change the key of the output?  If you are creating sound to go along with a song, would it be possible to notate the chords in the song and create an output that follows the same chord structure?

**Comment by schrum2** [comment]
@annazwicker I believe that frequency and pitch are actually the same thing. Currently, in both Breedesizer and the SoundRemixer, the frequency is fixed and the sound is played at that fixed frequency. You should first see what happens if you change the play-back frequency (see if I'm right). Then, we can experiment to see if we can evolve the frequency. We could either have a fixed frequency for each sound sample, or the frequency itself could vary across the playback

**Comment by annazwicker** [comment]
@schrum2 They are the same thing (I wasn't thinking of pitch in terms of frequency).  I think it would make more sense for the frequency itself to vary across the playback, since it would sound a bit more like an accompaniment.  Evolving the frequency would be something interesting to play around with, and I also want to see if there's a way to add more than one note (or if the frequency is going to vary across the playback, more than one line of accompaniment).

**Comment by annazwicker** [comment]
Adding a second line could potentially be difficult with the given code, since the current code only handles one frequency.  It would also be challenging to figure out how to make the two pitches play simultaneously (depending on what you are listening for, you might want them to play simultaneously or you might want them to differ in both pitch and rhythm).  Going off of my previous comment, this could open up a lot of possibilities if you have two separate lines in one single output.  You could have one static and one moving line, or two static or two moving lines (this would be interesting to explore, specifically the idea of having one static and one moving line.  It would be wise to make sure the static line goes with the majority of the original audio file to keep dissonances to a minimum.  This can vary in difficulty depending on the length of the piece).  Pitches that go together in a consonant chord is also something to consider when coding, since consonant chords are usually much more preferable to dissonant chords.  You would not only have to make sure the two starting pitches are consonant, but you would also have to make sure they remain so if you decided to have the notes vary across the playback.  Whether or not you prefer consonant or dissonant chords could also depend on the original audio file you are trying to compare the outputs to.  You would have to change the graphical displays of the outputs, likely with two different colors to represent two different notes.  We would also need a way to keep track of the original code (one pitch) and the new code (two pitches).

**Comment by schrum2** [comment]
I'm going to close this issue. It is a bit ill-defined, since we're not really sure what success would look like. We would like to somehow remix the sounds, but there isn't an obvious way to do that nicely, and we seem stuck.
