### ISSUE TITLE
Evolving in SparCraft

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#116]
This issue cannot be attempted until #108 is completed. Once you have a working Java agent for SparCraft in the MM-NEAT code base, you need to make a SparCraftTask class that actually evolves agents to play the game. We will need to discuss how to set this up.

**Comment by Squillyprice01** [comment]
In trying to do this and related issues involving StarCraft AI, I learned some things that will be helpful to anyone interested in the future.

Firstly, abandon any and all hopes of writing the code in Java. There are false leads out there that make it seem possible (JNIBWAPI), but that is all they are. JNIBWAPI was the only Java code I managed to interface with the game, but it was buggy and a major version behind the state of the code injector (V 3.*.* vs 4.*.*). Even if you could get an agent working, it would be unable to compete. C++ is the only way to do that.

Another thing I learned is that in order to be able to run all of the software needed to interface with StarCraft, Admin privileges on the system are 100% essential. You cannot do anything without admin privileges.

**Comment by schrum2** [comment]
Giving up on StarCraft in Java
