### ISSUE TITLE
Implement 3d and pooling layers in convolutional NN

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#123]

**Comment by schrum2** [comment]
I definitely agree that pooling layers could be relevant in the long run, but they are only necessary for dimensionality reduction. Though the Tetris game board is 10 by 20, this is too small for pooling to make any sense. 

Additionally, despite the effectiveness of CNNs, there are some signs that the pooling operation specifically has some negative qualities: https://towardsdatascience.com/what-is-wrong-with-convolutional-neural-networks-75c2ba8fbd6f

It would still be worth implementing if we want to solve a particularly large problem though. For example, we could try evolving HyperNEAT networks for Doom, but this is a domain where the CNNs really do need pooling because the input space is so large. Not Tetris though.

**Comment by schrum2** [comment]
This is on indefinite hold. The idea of 3D convolutions is not relevant, but pooling could be specifically useful in VizDoom, perhaps.

**Comment by schrum2** [comment]
VizDoom is not longer part of the repo, and we're not doing work with HyperNEAT anymore
