### ISSUE TITLE
Debug newly integrated popacman code!

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#134]
Once we completely debug this new code, #21 should be complete.

**Comment by schrum2** [comment]
I think one of the map nodes being sent to some method is invalid because
of the partial observability. Probably caused by one of those GameFacade
methods that returns -1.

Even though we are using the PO code, we should turn the po setting in
CustomExecutor off. This should be identical to the original code and is a
better first test.

**Comment by Squillyprice01** [comment]
There are no longer any errors in execution!
