### ISSUE TITLE
More flexible substrate network architectures

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#16]
From MM-NEATv2: https://github.com/schrum2/MM-NEATv2/issues/457

I think this issue is a MUST DO.

**Comment by schrum2** [comment]
Recent progress on #33 makes completing this issue even more important. In particular, Having different substrate sizes and also different kernel (receptive field) sizes at each level could be useful.

**Comment by schrum2** [comment]
@leg2015 Now that there is an interface for defining substrate architectures, start by implementing that interface to define the LeNet architecture. This is pretty much just a simple test ... the code isn't really set up to train on the digit data.

Next, override/modify the getSubstrateInformation in HyperNEATUtil to return the list of Substrates based on a provided substrate configuration (pass in a list of Triple). Try to extract code that will be re-used (regarding inputs and outputs) into helper methods.

Lastly, the specific SubstrateArchitectureDefinition used should be defined as a class Parameter. The default value will be null, in which case the code should rely on using the HNProcessWidth and HNProcessDepth parameters, the way it currently does.

Once all of this is implemented, submit a pull request for me to review.

**Comment by schrum2** [comment]
This issue is almost done, but has errors right? I don't want it forgotten. Make sure we go over it tomorrow.

**Comment by DevonFulcher** [comment]
Whether or not a connection is convolutional or not is determined in a contrived way that depends on the size of the network. This should be fixed later to allow for a way to choose arbitrary architecture. Deeper connections in the network are very saturated. This could be fixed with the RELU activation function or batch normalization. Other ways to generalize are here #39 and here #122.
