### ISSUE TITLE
Build VariableDirectionSortedPossibleGhostDistanceBlock and put it in POCheckEachDirectionMediator

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#190]
This block sorts distances of possible ghosts. Possible ghosts are those that we can see or those that we have a probable location for. As of right now, all possible ghosts are considered equal, even one with a 100% probability (i.e. we can see it) and ones with a .00001% probability. It might be good to consider the probability of a ghost when sorting the locations.

#142 

#165

**Comment by Squillyprice01** [comment]
I think it is in working order. It runs! @schrum2

**Comment by schrum2** [comment]
Make a separate sensor block that indicates the certainty of the Nth closes ghost. The VariableDirectionSortedPossibleGhostDistanceBlock that you have already made can sense the distance to the 1st, 2nd, 3rd, etc closes possible ghost. This new sensor block would sense the certainty that the sensed ghost is actually there, so each of these sensors would directly correspond to the thing being sensed by VariableDirectionSortedPossibleGhostDistanceBlock.

If the ghost can be seen, then the certainty sense it 1.0, and otherwise it is the probability value.

**Comment by Squillyprice01** [comment]
This sensor is added to POCheckEachDirectionMediator. There, sensors are created for the four closest ghosts (1st, 2nd, 3rd, 4th each get a sensor). As it stands, this will keep track of the nearest four ghosts, but with probabilities, there can be many more than just four probable ghosts.

**Comment by Squillyprice01** [comment]
Now it compares ghosts in a specific direction.

**Comment by Squillyprice01** [comment]
This is done!
