### ISSUE TITLE
Allow HyperNEAT CPPNs to have recurrent links

### ISSUE THREAD

**Issue by DevonFulcher** [schrum2/MM-NEAT#259]
Maybe the genotype will store some memory of what it has learned from layer 1 to apply to layer 2

"The network's memory would be subject to the arbitrary order that we query links in, but this could still be helpful, and might even break up the regularity that we experience when using HyperNEAT" - Schrum

**Comment by schrum2** [comment]
The commit above explains why I'm closing this issue.

Note that the above commit was to dev branch, because I was having visualization errors in dev_tetris (I know that the visualizations here are still being refactored). Still, if you want to see the recurrent links in the visualization, you will need to fix the visualization first (or run batch files from dev)
