### ISSUE TITLE
Issues with wox.serial Util.java and AccessTest.java on personal machine

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#285]
I am getting the error "ReflectionFactory.GetReflectionFactoryAction cannot be resolved to a type" in the two files listed above.

![screenshot 123](https://user-images.githubusercontent.com/15305479/43374432-4d1b4136-9375-11e8-9460-c4d19f3d4ef3.png)
![screenshot 124](https://user-images.githubusercontent.com/15305479/43374433-4d30559e-9375-11e8-9990-54de8a351acd.png)

**Comment by schrum2** [comment]
Set your PATH variable to point to the new JDK's bin directory: https://www.java.com/en/download/help/path.xml
Note that your PATH probably already has a reference to some JDK, so you will need to remove the old one and replace it with the new one.

For Maven, you may also need to set JAVA_HOME, but if Maven install works in Eclipse then this second step probably isn't necessary: https://maven.apache.org/install.html

**Comment by schrum2** [comment]
Concerning the ReflectionFactory.GetReflectionFactoryAction error. I actually found a better explanation for this. It turns out that you aren't supposed to use the sun package, even though it is technically part of the Java SDK. It is not meant to be part of user code. However, I found a Maven repo that can download a jar with this package instead, which makes things work smoother right out of the box. I just committed this to dev, and will soon merge it into master as well.

I'll hold off on merging it into your current pacman branch since you seem to have found a workaround, and I don't want to mess up your code while you are working on it for capstone.

**Comment by Jiadalee** [comment]
@schrum2 where can we download this Jar with the ReflectionFactory.GetReflectionFactoryAction package?

**Comment by schrum2** [comment]
@Jiadalee I'm pretty sure this commit is referring to this commit:
https://github.com/schrum2/MM-NEAT/commit/2e55469539a58c573b028aef1bf8f4a3ad2919e7
But I don't think I actually have a jar that contains ReflectionFactory.GetReflectionFactoryAction ... not sure what I meant at the time. This is another ongoing issue: https://github.com/schrum2/MM-NEAT/issues/348

As it is, MM-NEAT will definitely not work with the newer versions of Java since it relies on wox, which relies on non-API code in the Sun SDK. The tutorial (https://github.com/schrum2/MM-NEAT/blob/master/TUTORIAL.md) clarifies that you need to use Java 1.8

**Comment by Jiadalee** [comment]
@schrum2 Yes. I'm using JDK 11, but this does not include the `ReflectionFactory.GetReflectionFactoryAction` . I'm wondering if there is a solution for this issue since I dont wanna shift back to JDK 1.8.

**Comment by schrum2** [comment]
@Jiadalee You can have both JDK's installed on your system and switch between them as needed. How complicated this is depends on your setup. I tend to use Eclipse, which has built-in Maven integration and allows for easy use of different JDK configurations on a per-project basis. However, if you are working with Maven from the command line then you would need to keep changing your JAVA_HOME setting to switch back and forth ... I believe there is a tool that allows for easy switching between Java versions at the command line, but I do not have personal experience.

In any case, I hope to eventually make my code function with the latest version of Java, but it definitely won't be happening any time soon.
