### ISSUE TITLE
Get Accelerated Neuroevolution Working

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#312]
After closing a basic issue ( #311 ) you should turn your attention to this main issue. Focus on getting your copy of Accelerated Neuroevolution to work:
https://github.com/nazaruka/deep-neuroevolution

Even though that it a different code base, you can track progress and challenges related to that issue here. Eventually, some of that work will hopefully be relevant to this codebase.

**Comment by nazaruka** [comment]
Unfortunately, **the directory seems to be incompatible with Windows and better suited for Unix-like environments.** Every step of the tutorial seemed to be feasible until it was finally time to launch `local_run_redis`.

The following is my attempt at running the redis in Git Bash:
```
Admin@Alex MINGW64 ~/Desktop/Southwestern/SCOPE/Files/Repo/deep-neuroevolution (master)
$ . scripts/local_run_redis.sh
bash: tmux: command not found
bash: tmux: command not found
bash: tmux: command not found
bash: tmux: command not found
bash: tmux: command not found
```
When examining the contents of `local_run_redis`, I noticed several commands demanding `tmux`, which is a command used to generate multiple terminal windows in Linux builds and in Mac. Because we cannot execute this command on Windows, we cannot launch the redis and therefore cannot make full use of this directory on our Windows machines.

**_NB:_** Attempting to launch `local_run_exp` gave me a similar output, just with seven lines of `bash: tmux: command not found` instead of five.
