### ISSUE TITLE
Integrate CMA-ES into MM-NEAT

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#313]
Now that the code is available ( #302 ) I want to actually integrate it. Specifically, everything in MM-NEAT depends on applying an EA to a Task. I'm not sure what the best approach to accomplish this is, but I want to make it possible to treat CMA-ES as a standard EA that can evolve solutions for Tasks. 

Look at LimitedSinglePopulationGenerationalEAExperiment, SinglePopulationGenerationalEA, and LonerTask. We need to have a way of treating CMA-ES as the EA to evolve in a LonerTask. This will probably involve making some kind of facade class that essentially calls existing methods of CMA-ES, but juggles the parameters and return values a bit. 

This should be a complex issue, so please discuss ideas and restrictions directly in this thread.

**Comment by schrum2** [comment]
I still want to do this @MBatt1 , and since you worked with @jakegut on your AI project, you at least know what CMA-ES is and have an idea of what it can do. Jake is actually the one that originally copied the CMA-ES code into this, but never got around to fully integrating it. In this issue thread, there is a reference to a closed issue #314 which was never actually completed. Although I said it wasn't worth the effort, that MarioGAN domain is still a good test domain for CMA-ES once you get it working.

**Comment by MBatt1** [comment]
Created CMAESMarioGan for testing, however the current evaluation function needs to be tweaked to be functional.

**Comment by schrum2** [comment]
This reminds me ... since CMA-ES is an optimizer, it might actually be trying to **minimize** the score rather than maximize it. If this is true, we would need to put a negative sign in front of the result returned by the valueOf function. However, even with this fix, the value of the stopping value needs to change ... maybe an unreasonable value of -9999 would be a good place to start, since that should be unobtainable. Need to play around with numbers and see what happens.

**Comment by MBatt1** [comment]
There is a strange assert in setWeights(double[] weights) when parameters are supplemented in the CMA-ES code which always fails, so it has been commented out to allow it to properly run.
Because CMA-ES is a minimizer, scores have to be minimzed prior to being given to CMA-ES, however the output files still use the un-negated data. 
CMA-ES does things differently than the other EAs, and so the generateChildren and selection methods do not work the same, and instead have method calls to CMA-ES that function essentially the same. When converting the "children" collected from CMA-ES, it needs to be converted to `ArrayList<Genotype<ArrayList<Double>>>`, and so a new method is available in PopulationUtil if this is needed for anything else.

**Comment by MBatt1** [comment]
CMA-ES appears to be fully functional

**Comment by MBatt1** [comment]
Not sure if genomes are being created with the correct length, it is always 10, but it hasn't crashed.

**Comment by MBatt1** [comment]
Now is dependent on bound length
