### ISSUE TITLE
Post Eval Watch on Mario GAN Level Evolution Crashes

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#318]
Tried running this comment:
```
postAllBestObjectiveWatch.bat mariogan MarioGAN OverWorld4Segments 0 1
```
After evolving with default settings (running main method of edu.southwestern.tasks.mario.MarioGANLevelTask , but received NullPointerException

**Comment by schrum2** [comment]
I just tried this and it actually worked fine. However, I did get an error the first time I tried, but it was simply because the version of the jar I had maven compiled was incompatible with the code. When I ran the post-watch command from in Eclipse it worked, and let me play using the keyboard, so I'm closing this issue.
