### ISSUE TITLE
Random key placement sometimes unreachable

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#349]
When adding keys to a level, they need to be reachable by the player. So implement a search algorithm (most likely A*) to see if the key is reachable to at least one door.

**Comment by schrum2** [comment]
I think this issue will be completely subsumed by #347 since A* can account for the number of keys encountered/possessed as part of the state. However, we might want to think of more clever heuristics than pure Manhattan distance to assure that the agent doesn't waste time exploring around locked doors it doesn't have a key for. This is only an efficiency issue though ... get the A* solution working in general, and if it proves too slow we will improve the heuristic.

**Comment by schrum2** [comment]
I think that our use of A* combined with the grammar based generation makes this no longer an issue.

Close if you agree.
