### ISSUE TITLE
Simplified A* State Representation for Zelda Dungeon

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#359]

**Comment by schrum2** [comment]
This issue needs more context. I think that originally this was supposed to aid efficiency, but now that we are checking the GAN dungeons for play-ability, it no longer seems feasible to reduce the state space to just the room ... we need to force Link to explore the level in order to find out how to beat it.

Should we keep this issue open or close it?

**Comment by jakeryang** [comment]
Originally this was to improve the efficiency of the state. However, the current state does fine on its own. I only see this state being implemented to see if the key matches a locked door so that you don't bypass a door without having the key, but this has been fine as well. Closing.
