### ISSUE TITLE
Make new game, move away from rouge-like

### ISSUE THREAD

**Issue by jakeryang** [schrum2/MM-NEAT#380]
The rouge-like prototype for testing dungeons has proven to be beneficial, but it lacks in some areas. I would like to create a new game to be able to have more features such as movable traps. Basically, go away from the turn-based game to a more modern experience. There seems to be a simple game engine (https://litiengine.com/) that can do the job as it's made with tile-based maps in mind. There are plenty of other resources and engines that can do this with animation support. This is something I can work on after SCOPE.

**Comment by schrum2** [comment]
That sounds awesome if it is something you want to do on your own. We can make the study work either way, and I'm pretty sure that nothing in the study proposal will depend on the game engine details, so we can get that stuff prepared in advance.

You might want to consider some other engines first. This is more Zelda specific:
https://github.com/kennycason/java_games
The writer recommends this:
https://libgdx.badlogicgames.com/

There is also this C++ engine that looks pretty awesome:
https://www.solarus-games.org/
I'm not sure if you would want to start a new repo, or try to re-use the existing Java code. The Java Graph Grammar code creates a bunch of text files anyway, right? So maybe you set up the engine in C++ to read files created by the Java Graph Grammar code, along with rooms created by the Python Zelda GAN code. Sounds complicated, but maybe better then the alternatives?

In any case, these are all just recommendations. Since you will be working on this pretty independently, you should feel free to pursue whichever approach you prefer. Perhaps using the original Java engine you proposed is more appealing to you, despite the fact that it is not geared specifically at Zelda, because you want to learn more about game programming. It's up to you.

**Comment by jakeryang** [comment]
> The writer recommends this:
> https://libgdx.badlogicgames.com/

I've heard good things about libGDX, it seems like the go-to for Java game development. However, libGDX uses Gradle to build the project. Is this something that we can incorporate in the MM-NEAT codebase or will I have to start a new project? There appears to be a Maven repo for libGDX, but it still seems somewhat complicated for a larger codebase.



> There is also this C++ engine that looks pretty awesome:
> https://www.solarus-games.org/

This was actually the engine used in the paper I was looking at, that was specifically applying graph grammars to Legend of Zelda. However, it doesn't seem I have much control over the engine as it's specifically made for A-RPGs.

The original engine I referenced to has poor documentation, so I probably won't be using that.

**Comment by schrum2** [comment]
Since @jakeryang has started the repo here ( https://github.com/jakeryang/ZeldaDungeons ) there is not more need to maintain this issue in the MM-NEAT repo ... closing.
