### ISSUE TITLE
Too Many Triforces HumanSubjectStudy2019

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#458]
Running HumanSubjectStudy2019 with InterestingZeldaGraph uses a set of backbone parameters that somehow generates three Triforces that all work as ending points. Additionally, running HumanSubjectStudy2019 with TwoTriforceBugGraph produces two Triforces.

**Comment by schrum2** [comment]
Take another look at this when you get a chance. I've looked into it and am still confused. My recommendation for the next thing to investigate is to attempt printing or otherwise evaluating what ``graph`` looks like after ``grammar.applyRules(graph)`` to see if the level already has multiple Triforces ("t" symbols) at this point. Basically, we need to figure out if the error is in ``grammar.applyRules`` or in ``DungeonUtil.recursiveGenerateDungeon``

**Comment by cappsb** [comment]
There is also a way of setting the rules to make multiple rafts

**Comment by cappsb** [comment]
It seems as though when it tries to process a pair of non-terminal inputs for which there is no rule as of yet, it either throws a null-pointer exception of behaves strangely. One of the pairs is ENEMY_S, TREASURE. I figure that if there are multiple ENEMY_S's that have no pairings, they may just pair to the end, thereby giving multiple ENEMY TREASURE pairings resulting in multiple Triforces. Further digging required.

**Comment by cappsb** [comment]
Changed findRule(T start) to keep undefined rules from going haywire. Originally its design was to map rules which had no end node to itself, but since it only checked startNode and not endNode, it allowed crazy stuff to happen like multiple mappings of ENEMY_S to TREASURE. Appears to be fixed, all my testing to try and replicate it has failed.
