### ISSUE TITLE
A* model to solve json Mega Man levels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#505]
Given that we can convert either VGLC or MMLV files to json format (representing an entire level) we should also come up with a single A* model (define a MegaManState class) that allows a solution path for the levels to be determined. For comparison, refer to MarioState and LodeRunnerState.

**Comment by cappsb** [comment]
The search algorithm fails on the following levels:
Level three: the jump height of three does not allow for the agent to traverse past the first screen. When changed to a jump height of four, the appearing/disappearing blocks are mapping to solid and the agent is hitting its head so cannot traverse jumping puzzle, so it cannot complete the level.
Level seven: You need the platform gun in order to traverse through the Hazard room
