### ISSUE TITLE
Direct editing of evolved Lode Runner levels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#522]
The IceCreamYou code allows for direct editing of Lode Runner levels. This could be very useful in fixing levels generated by the GAN that are close to beatable, but not quite there. However, because of changes made to the IceCreamYou code to enable it to launch levels passed in from the GAN (not from a saved file), the editing doesn't work properly.

Currently, if you click Edit, you will be able to modify the level provided by the GAN (I'm using the Interactive GAN interface). If you then click save, you are prompted to provide a filename, and at this point it looks like you will be able to play your edited level ... however, clicking Play at this point transforms the level back to the way it used to be. 

Somehow, the changes made before clicking Save need to modify the level representation inside of the IceCreamYou code so that you can play the modified level. Also, I don't think the "saved" level was every written to file anywhere, which is also an issue.

Note that any changes to the level here will NOT be able to be copied back into the interactive GAN evolution interface. In this interface, all levels are represented as latent vectors, so modifying the level they produce does not/cannot affect the genotype itself. These modifications are only on the IceCreamYou side, for the player's enjoyment.

**Comment by schrum2** [comment]
One more bit of useful information on this. Apparently, when I clicked save, it produced an error. I tried to name my file "FIXED" and this led to the following error in the console:
`Error: src\main\java\icecreamyou\LodeRunner\src\main\java\icecreamyou\LodeRunner\FIXED-level.txt (The system cannot find the path specified)`

It looks like it repeated the save path twice before specifying the file name. If you simply fix this part of the problem, then saving will probably work, which will likely make the modified level playable.

However, it would also be nice if the modified level could be played without actually saving it to disk first.

**Comment by kdsteckel** [comment]
Double file path issue fixed by removing the file path from the save method in the level class. The levels that get edited are now saved to that directory, but when you hit play it still reverts back to the original GAN level. You can go and play your edited level if you choose it from the list of levels. 
I believe that if we change the implementation of the edit button in the LodeRunner(List<List<Integer>> level) constructor that we could play these levels straight off the bat without having to navigate to them. Also, I might need to write a new constructor for the LevelSaveDialog.java class to be specific for levels from the GAN, just like the GAN specific constructor for LodeRunner(List<List<Integer>> level1) and Level(List<List<Integer>> level). Or maybe remove this for GAN level, I'm not sure what the best way to do it would be I'll have to fiddle with it to see. 
I am not going to force commit the FIXED-level.txt because the ultimate goal is to make the GAN levels be editable and then immediately playable. 
@schrum2

**Comment by kdsteckel** [comment]
Maybe have a boolean value to control if it is in interactive mode or regular mode. 
Maybe have a save, yes or no, prompt when editing was done to save or not.

**Comment by kdsteckel** [comment]
I think I'm going to need to rethink how I am going about this because using the reset() method always reverts it back to the original level. I have it so that it will let you edit and when you press the "Play Level Now" button it keep the edited level on the screen, but does not let you play even though I set the mode to Mode.MODE_PLAYING. So far I have not figured out how to make it start playing the level, but that is what I am going to continue tomorrow morning. I am hoping it can be done without much refactoring, but it is possible that I will have to write a lot of additional code in the IceCreamYou code for this to be able to work.
@schrum2

**Comment by kdsteckel** [comment]
I think that this issue is pretty close to being done unless there are more features you want me to add. Can you check and let me know? @schrum2

**Comment by schrum2** [comment]
I think there was a miscommunication about the buttons. Here is the scenario I want:
1.  Player chooses to play a level, and actually moves around collecting treasures
2. Next, the player chooses to edit the level in some way
3. Here there are two options: 
3.a. Resume play in edited level with treasures already collected
3.b. Reset player to spawn point and treasures (but maintain other edits) and start playing

However ... it now occurs to me that it doesn't really make sense to edit treasures if they could pop back into existence depending on which button you press. Therefore, let's revise things a bit:

In step 2, whenever Edit is clicked, first reset the level (meaning the treasures and the player location) before allowing editing. This change means that 3.a and 3.b are identical, and thus we do not need both options.

**Comment by schrum2** [comment]
Finally figures this out. Closing.
