### ISSUE TITLE
Separate UP, DOWN, HORIZONTAL models for Mega Man

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#537]
I think that part of the problem with the Mega Man levels is that if you generate a vertical segment, it could have been for moving up or down. The downward segments don't have ladders, which is why it is impossible to beat many generated levels.

So, you need to make separate training sets for the upward and downward vertical segments. Then when we generate levels, we'll actually use three models: H, U, D. This three model approach should simply replace the 2 model approach (H+V). You do not need to maintain backwards compatibility with H+V, and can instead rename, change, and delete the code that supported it in favor of supporting this 3 model approach.

This issue will affect the current outstanding interface requests for issue #523 so complete this issue first and then change the interface requests in #523 accordingly.

**Comment by schrum2** [comment]
I like how the three buttons appear and disappear when clicking UseThreeGANs, but the original SetGANModel button should disappear whenever the other three buttons are present. 

Also, I found that if I switch to an exclusively VERTICAL model before clicking UseThreeGANs, then the levels remain exclusively vertical even after selecting UseThreeGANs, which is a problem.

**Comment by cappsb** [comment]
Before:
![image](https://user-images.githubusercontent.com/63438571/85067132-ce616200-b175-11ea-95b1-afd6cdab8c58.png)


After:
![image](https://user-images.githubusercontent.com/63438571/85067164-da4d2400-b175-11ea-9dc3-6b94d61cd8cd.png)

**Comment by cappsb** [comment]
Working with three GANs works, but now that each training set is so specific, it means that corners are really hard. We need to find a way to somehow allow connectivity when transitioning. Like if we could somehow have a screen for PresetUpperRightCorner, so that when the GAN places from UP to Right it places UP, then it places the corner piece, then places right. This might be fixed using objective evolution but if not then it will be a huge problem.
