### ISSUE TITLE
Breakable blocks do not display

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#551]
![image](https://user-images.githubusercontent.com/8397236/85490003-90f63d80-b596-11ea-849d-a5d0c0f786af.png)
This compares the level in Mega Man Maker with the MM-NEAT visualization

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/85589952-a0629e80-b609-11ea-9dc4-d4df297c6bfa.png)

**Comment by cappsb** [comment]
Since breakable blocks as seen in MegaManMaker are comprised of four different tile types, I used the original game's image. Basically in this state, the GAN generates one breakable block at a time, and in the conversion to mmlv, breakable blocks are formatted properly. In other words, this rendering is purely what the computer reads, but playing it will be slightly different.
