### ISSUE TITLE
Allow for LEFT level generation

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#561]
In mmlv example levels, there are some segments that are placed to the left of another. Make placing to the left possible.

**Comment by schrum2** [comment]
Related to this: currently, GAN and CPPN2GAN do segment placement differently. We need to modify the code so that evolving Direct2GAN can be done in the same way as CPPN. Specifically, I think Direct2GAN currently takes the first latent variable of each vector and uses it as a random seed. Instead, each direct portion should have an auxiliary variable that acts like the additional CPPN output

**Comment by schrum2** [comment]
Also want to be able to turn LEFT segments on/off via command line param

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/86815948-df044a00-c048-11ea-991f-ba0651b1cbe0.png)
Left generation works!

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/86817325-80d86680-c04a-11ea-9ec4-c9da39e5cf6b.png)
Left generation works with CPPN2GAN as well

**Comment by schrum2** [comment]
Works for Direct and CPPN!
