### ISSUE TITLE
Experiments Comparing ME-Line and MAP-Elites

### ISSUE THREAD

**Issue by MBatt1** [schrum2/MM-NEAT#693]
As an extension of #686, the following runs should be done with ME-Line to be compared to normal MAP-Elites

* Mario
  * DecorateNSLeniency
  * DistinctNSDecorate
  * KL Div (but on what levels? Wait until #630 is closed)
  * Novelty? but what to combine with?
* Zelda
  * DistinctBTRooms
  * WallWaterRooms
  * Novelty? but what to combine with?
* Lode Runner (all On20GAN)
  * GroundTreasureEnemies (PercentGroundNumGoldAndEnemies)
  * PercentConnectedGroundAndLadders
  * KL Div (but on what levels? Wait until #630 is closed)
* Mega Man (all MultiGAN)
  * DistinctVerticalAndConnectivity  
  * NoveltyVerticalAndConnectivity

Should be run through the launchMultiple.bat batch file in batches of 10 for each. Will be backed up to Google Drive

**Comment by schrum2** [comment]
Add experiments with the general latent vector scheme to this when #659 is completed. Do experiments chopping the latent vector into both 2 and 3 chunks, but divide the bins per dimension so that the total number of bins is comparable. For example, with 2 chunks, you could divide into 64 per dimension, and with 3 chunks you could divide by 16, because 64*64 = 16*16*16
https://www.wolframalpha.com/input/?i=y+%3D+%28x%5E2%29%5E%281%2F3%29+integer+solutions

**Comment by schrum2** [comment]
Apparently, ME-Line is really no better than MAP-Elites in pretty much any of the games. Here are some plots (more are stored in Google Drive):

Lode Runner QD scores
![AVG-prelim_loderunner20gancomparebins2-QD](https://user-images.githubusercontent.com/8397236/123835581-553f3380-d8ce-11eb-8389-f96b8b7ec874.png)

Mario QD Scores
![AVG-prelim_mariocomparebins2-QD](https://user-images.githubusercontent.com/8397236/123835607-5ec89b80-d8ce-11eb-97e5-e9aecfc16bd1.png)

Mega Man QD Scores
![AVG-prelim_mariocomparebins2-QD](https://user-images.githubusercontent.com/8397236/123835643-6a1bc700-d8ce-11eb-8486-c2556b5b7b69.png)

Zelda QD Scores
![AVG-prelim_mariocomparebins2-QD](https://user-images.githubusercontent.com/8397236/123835681-74d65c00-d8ce-11eb-88fe-52dc7e80aa16.png)
