### ISSUE TITLE
Boundary issues for sphere function

### ISSUE THREAD

**Issue by MBatt1** [schrum2/MM-NEAT#694]
![image](https://user-images.githubusercontent.com/53229958/121750170-80094980-cad1-11eb-9e77-6bc0b8bcf37c.png)
![image](https://user-images.githubusercontent.com/53229958/121926413-8da61580-cd03-11eb-8f2f-11e77c76defc.png)

When running sphere function optimization with CMA-ME or normal MAP-Elites, there appears to be a strange restriction that limits bins to within a central 1/4th square. Strangely, switching polynomial mutation off for MAP-Elites fixes the issue, but doesn't explain why CMA-ME has the issue.

_Originally posted by @MBatt1 in https://github.com/schrum2/MM-NEAT/issues/664#issuecomment-860820060_

**Comment by MBatt1** [comment]
![image](https://user-images.githubusercontent.com/53229958/122110968-cc5fcc80-cde4-11eb-834d-b3ead5b4f1b8.png)
for some reason it worked when I just finished a run

**Comment by schrum2** [comment]
We'll have to have multiple rounds of verification before we accept that this actually works

**Comment by schrum2** [comment]
I ran Sphere function using plain MAP-Elites with polynomial mutation turned on, and did NOT have any boundary issues:
![image](https://user-images.githubusercontent.com/8397236/122242530-04205000-ce89-11eb-9ac4-545a995e341d.png)

I guess the earlier result was caused by something weird that we fixed. However, I'm going to run with CMA-ME now to see if we run into problems there.

**Comment by MBatt1** [comment]
Since the results for MAP Elites and CMA-ME do not appear to be bounded any more, this is currently not an issue.
