### ISSUE TITLE
Eliminate duplicate code in constructors for SegmentCopyMutation and SegmentSwapMutation

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#746]
Both of these constructors need information on the number of segments in the evolved levels, as well as the indices where auxiliary variables start and end. The code is nearly identical in both constructors, and those the repetition should be eliminated.

Once solution would be to make both classes extend an abstract base class simply called SegmentMutation.

**Comment by alejmedinajr** [comment]
My current commit is where I completed a portion of this task, specifically the refactoring repeated code in both constructors and creation of an abstract base class called SegmentMutation.

**Comment by alejmedinajr** [comment]
The most recent commit for this issue passes the junit tests unlike the previous one. The problem occurred because I forgot to delete a line of similar code from the super class and class using the super class. I also did not include a line in the super class that called another super class. I also added some comments to the SegmentMutation class since it was newly created.
