### ISSUE TITLE
Fix MAP Elites initialization for Minecraft

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#778]
Initialized shapes may not match what persists in the world. Need to fix

**Comment by MuellMark** [comment]
Added in code in MapElites that clears the archive space and then adds in the correct shapes after initialization. I have it set up so that nothing generates during initialization also, to avoid confusion (This is a very quick change if we want to change this). I also had to fix how the clear method works for 1D shapes to ensure the ground doidn
t get erased, but now it should all be working. For smaller ranges, the archive could get completely filled out, especially with 2x2x2, but this isn't the case for larger ranges (4x4x4 and on).

**Comment by MuellMark** [comment]
I tested the minecraft code and that still works

**Comment by schrum2** [comment]
I've also confirmed that the MAP Elites code works on other domains still, so I'm closing now
