### ISSUE TITLE
Minecraft CPPN that simply has one output to define the block type

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#784]
As with #773 I would like to have a CPPN approach that just has one neuron that outputs the block type instead of doing an argmax across several options. There will be a command line parameter to control this.

Replace the block type outputs with one output. We will need to restrict the output to the range [0,1] (how best to do this?).

Given this restricted range, multiply the output by the number of available block types then round down to get an index in the block list. That is the block to generate.

**Comment by alejmedinajr** [comment]
The command line parameter, `"oneOutputLabelForBlockTypeCPPN"` ,was made, and it seems to be working fine when `"oneOutputLabelForBlockTypeCPPN"` is true (there are 8 output labels rather than 13 and the shapes generated still seem to contain a good variety of blocks from the block set). 

Also I could not think of a better name for the command line parameter. It is rather long, so maybe there is a better name that is shorter for it (or even better at describing it).

**Comment by schrum2** [comment]
If this isn't working, then please fix it.

**Comment by alejmedinajr** [comment]
Turns out it was/is working.
