### ISSUE TITLE
Benchmark Parallel Init in Minecraft

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#787]
Try running some experiments with parallelMAPElitesInitialize set to true and set to false. Time each and compare. I want to know if we are getting a tangible benefit. You may need to increase either parallelMinecraftSlots and/or mu to notice a difference. Report results in this issue thread.

**Comment by alejmedinajr** [comment]
I ran both for the same amount of time ("roughly three minutes") just to see if there would be an immediate difference.

This first image is the result for when parallelism is set to True. 
![filledBinsParallelismTrue](https://user-images.githubusercontent.com/100097809/173447792-7ae6e546-f40f-4848-a9c9-477b0b147a41.png)

This next image is for when parallelism is set to False.
![filledBinsParallelismFalse](https://user-images.githubusercontent.com/100097809/173447972-3259cc67-d344-426b-8fd8-d9b0c1e21e02.png)


When parallelism is set to True, more bins were filled. However, this may be not be accurate of a decision just yet since the time both were run was only 3 minutes. I think I will run both on the two lab computers in the back for a longer duration of time.

**Comment by alejmedinajr** [comment]
I set up an actual timer to time the initialization, and the parallelism being true seems to make the initialization faster by ~1000 milliseconds. 

Parallelism is False:
![TimingResultsNOPARALLEL](https://user-images.githubusercontent.com/100097809/173451532-cf478c16-df44-4eb7-a8e7-f2e79276a937.png)

Parallelism is true:
![TimingResultsYESPARALLEL](https://user-images.githubusercontent.com/100097809/173451534-7f78ee96-5eb4-4e9f-98e0-2908f5fd77fa.png)

**Comment by schrum2** [comment]
Try with Change in Center of Mass since that takes a long time to compute. Parallelism could be more of a benefit there.

**Comment by alejmedinajr** [comment]
Timing with parallelism with center to mass:
![Parallelism with centertoMass](https://user-images.githubusercontent.com/100097809/173454406-ea92bb69-19d2-4d72-b1f5-7f40799e5832.png)

Timing with no parallelism with center to mass:
![No Parallelism with centertoMass](https://user-images.githubusercontent.com/100097809/173456752-782abcf2-9fca-4a1e-93a4-9da8c6c93ebc.png) 

I ran both of these tests with both parallelism and no parallelism using center to mass fitness. It looks like both were faster than the other fitness test that was run, which seems a little confusing.

**Comment by schrum2** [comment]
If the fitness function is literally the only thing that changed, then it is odd that the change in center of mass fitness would be faster. However, we might need to increase the delay time used to measure the fitness. We should look carefully at this together at some point

**Comment by alejmedinajr** [comment]
Did the same timing tests that I ran yesterday, below are the results. This test shows that parallelism being true is slower (although not significantly since a 1000 milliseconds is 1 second). 

Timing for when Parallelism is **False**:
![2022-06-14-ParallelismFalse](https://user-images.githubusercontent.com/100097809/173605183-ddc722af-306d-45f9-8978-2bab18fff494.png)

Timing for when Parallelism is **True**:
![2022-06-14-ParallelismTrue](https://user-images.githubusercontent.com/100097809/173605187-40a2ff4d-3bf3-4697-9b13-d7d1fdbb8f88.png)

**Comment by schrum2** [comment]
I think the Minecraft server might be a bottleneck that prevents us from seeing a large benefit from parallelism, but I'm not sure. I'm going to let this issue remain dormant for a while and revisit later.

**Comment by schrum2** [comment]
You can return to this. Try using change in center of mass fitness, setting minecraftEndEvalNoMovement to false, and making the minecraftMandatoryWaitTime a much bigger number.

**Comment by schrum2** [comment]
Since issue #774 was successfully closed, and parallelism definitely showed a benefit there, I'm going to close this issue. Focusing on getting  a little extra speed at the start is less important than getting speed through the whole of evolution.
