### ISSUE TITLE
Identify most fit elite(s) in archive

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#793]
At any given time, there is at least one elite in the MAP Elites archive that has the highest fitness (there could be a tie). In the Minecraft world, when visually depicting the archive, there should be a special identifying cube in the empty space around whichever shape has the highest fitness. Note that from issue #791 there are already plans to have emerald and diamond blocks in the spaces around the shapes, so a different identifying block will be needed, preferably one that is rare and we won't be using in flying machines ... how about a gold block? Let's place this gold block centered above the most fit shape. 

Naturally, if any other shape surpasses this one, the gold block will need to be eliminated, but there can be multiple shapes tied for best, so each would have the gold block.

Somewhat related: I'm currently trying to evolve flying machines with the change in center of mass fitness by running the code in `ChangeCenterOfMassFitness` and some shapes are supposedly getting a fitness of 8, but I don't think I'm seeing enough movement to justify this, hence my desire to identify the supposed champions.

**Comment by schrum2** [comment]
This probably makes most sense for @MuellMark to do since he is working on #791 as well, but whoever gets to it first can start, and then you can work together if desired.

**Comment by MuellMark** [comment]
This seems to be working with WidthDepthHeight, but it's still a little finicky at times, I'm running investigations to see what possible issues are

**Comment by MuellMark** [comment]
At this point, 1D, 2D and 3D archives should be able use this to display the champion. I tested this with all 3 characterizations using the occupied count fitness function. The most challenging part from this issue was having it interact with the interactive elements, but now when a shape is regenerated (with the diamond), the gold block is place with it. But, when the shape is removed from the archive (with the emerald block) and it is the champion, the gold block is put onto whatever the next champion is until a more fit champion is found. All of these incorporate the fact that there could be more than one champion at any given time, as they are tracked using a set. 

Champion found with the occupied count fitness
![Inked2022-06-16_15 46 54](https://user-images.githubusercontent.com/92736704/174160971-c3c0b491-b37e-4af1-9e4b-0733bad3dadf.jpg)
![2022-06-16_09 06 27](https://user-images.githubusercontent.com/92736704/174161069-df5ff5e1-4806-468b-a09e-d762a15e1b1d.png)
