### ISSUE TITLE
Force specific elite to create offspring

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#805]
Add another cube around each shape (how about crying obsidian?) that if destroyed, forces MAP Elites to generate offspring from that shape immediately (or at least, when the next opportunity arises). This new individual could be placed into the archive as usual. It gives use the ability to focus on what seem like the most promising individuals.

**Comment by schrum2** [comment]
The commit that was just made should make this issue easy to carry out. Just call the new
`public void newIndividual(int parentIndex)`
method

**Comment by MuellMark** [comment]
The obsidian block will be read in with the diamond and emerald, so we'll need to change the triple into a quadruple. Also, we might want to create a custom private inner class that contains the needed info for each block, but refers to each item clearly. This should make things less confusing for the future

**Comment by schrum2** [comment]
Specifically, the private inner class would be returned instead of the Quadruple. Maybe you could call the class ControlBlocks or something similar (if that description suits the first coordinates in the return group)

**Comment by MuellMark** [comment]
With the newest commit, we were able to use all three of the blocks past 900 shapes generated, we'll continue to verify that this is working tomorrow

**Comment by MuellMark** [comment]
The way these blocks are read in and stored has been changed to being a private class, rather than a triple/ quadruple, which makes things easier not only now, but also for the future if we want to add any additional blocks. The obsidian block is spawned in with the rest of the control blocks and is read in at the same point. The issues we had where the thread would crash, even without any input from the player, have been resolved by ensuring only one block's action can be cleared at a time. Once the obsidian is broken, new offspring from that shape should start being generated. It is difficult to test this, but we believe it should be working.
