### ISSUE TITLE
PistonVSAirBlocks

### ISSUE THREAD

**Issue by TjRaffert** [schrum2/MM-NEAT#885]
Create a test for counting air blocks and pistons.

**Comment by TjRaffert** [comment]
I committed the files to run this.

**Comment by schrum2** [comment]
Currently testing on my machine. It runs at least

**Comment by schrum2** [comment]
The AIR vs Piston binning scheme always assigns every shape to the bin for 0 air blocks. This is because the list of blocks sent to the NumAirFitness class doesn't actually include AIR blocks, since AIR is assumed to occupy the space of the world anyway. This means that NumAirFitness cannot simply extend TypeCountFitness, and instead needs to be written to extend MinecraftFitnessFunction directly.

What you should do is count the total number of blocks in the shape (none should be AIR), and then subtract that amount from the max possible volume of the shape (since all the other spots are assumed to contain air).

**Comment by schrum2** [comment]
I'm running this at home, combined with SBX. It seems to work now, but we'll need to wait and see if it produces flying machines.

**Comment by schrum2** [comment]
Here is what the final archive looks like for the Air vs Piston run with SBX. It gets decent coverage on the air block axis, not not along the piston axis. We discussed that it makes some amount of sense that there is not good coverage along the piston axis since there are so many block possibilities that turning them all to pistons is difficult.

![BigMinecraft-AirVSPistonSBX0_MAPElites](https://github.com/schrum2/MM-NEAT/assets/8397236/8ba7fb2f-0548-4513-b3fe-25452a26a705)

This run also did not produce any flying machines, which isn't too weird for 5x5x5 shapes, but is disappointing.

**Comment by schrum2** [comment]
This issue is done, but is transitioning into a new issue at #894
